### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ryanzhumich** [coastalcph/seq2sparql#1]
Hello, 

Thanks for creating such a great dataset!
Do you have license for it?

Best,
Rui

**Comment by ruixiangcui** [comment]
Hi Rui, thank you for your interest in our dataset! The license is [CC-BY license](https://creativecommons.org/licenses/by/4.0/). 

We would like to share the news that we are planning to release a preprint for the new version of CWQ, named MCWQ, very soon. The dataset is 11 times the size of the original CWQ. You can find more information on the [README](https://github.com/coastalcph/seq2sparql/blob/master/README.md) page.
