### ISSUE TITLE
Input file path in hf/run_mt5.sh

### ISSUE THREAD

**Issue by mihaela-bornea** [coastalcph/seq2sparql#5]
This is a very interesting dataset and the baseline and evaluation code are very helpful. 

I have a clarification question as the input path from the run scripts does not match exactly the structure of the data directory in your git repo. 

Please confirm if parameter values from [hf/run_mt5.sh](https://github.com/coastalcph/seq2sparql/blob/master/hf/run_mt5.sh):

```
--train_file ../data/translations/$split/train.$lang.json \
--validation_file ../data/translations/$split/dev.$lang.json \
--test_file ../data/translations/$split/test.$lang.json \
```

should point to 

```
../mcwq/translations/$split/train.$lang.sparql
../mcwq/translations/$split/train.$lang.txt

../mcwq/translations/$split/dev.$lang.sparql
../mcwq/translations/$split/dev.$lang.txt

../mcwq/translations/$split/test.$lang.sparql
../mcwq/translations/$split/test.$lang.txt
```

**Comment by ruixiangcui** [comment]
Hi Mihaela @mihaela-bornea , thanks for your interest and for pointing out the mistake! The JSON files are a concatenation of the question and query pairs. I have uploaded the files and the script. Please pull from the latest commit.
